// Public re-export of compliance-core proto-generated types.
//
// Consumers (`@compliance-core/server`, backend SDKs) import service definitions
// and message types from this barrel. The underlying files are regenerated by
// `pnpm proto:gen` (buf + @bufbuild/protoc-gen-es) and are NOT committed — see
// the proto-lint job in CI, which fails if generated output drifts from .proto
// sources.
//
// This file intentionally re-exports only from `./generated/**` so that
// consumers never have to know the generator's layout. If we swap Connect-ES
// for grpc-js-native, only this file changes.

// Generated types land here after `pnpm proto:gen`. Until then the module is
// intentionally empty so that `pnpm build` succeeds on a fresh checkout
// without requiring buf plugins to be network-reachable.
export {};
